### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [H-Haynes/TIMP#1]
大佬你好，我拉下项目之后安装了依赖，但是无法构建，这个是报错
```
D:\project\TIMP>cnpm run compile

> timp-music@2.0.0 compile
> npm run app:build && electron-builder build --config .electron-builder.config.js --dir --config.asar=false


> timp-music@2.0.0 app:build
> vite build && electron-builder

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.2.10 building for production...
✓ 49 modules transformed.
transforming (86) node_modules\.store\element-plus@2.7.2\node_modules\element-plus\es\components\carousel-item\style\index.mjsvite v5.2.10 building for production...
✓ 3 modules transformed.
dist-electron/main/index.js  5.12 kB │ gzip: 2.05 kB
✓ built in 661ms
vite v5.2.10 building for production...
✓ 1 modules transformed.
dist-electron/preload/index.js  1.79 kB │ gzip: 0.85 kB
✓ built in 307ms
x Build failed in 2.82s
error during build:
Error: [vite]: Rollup failed to resolve import "lodash-es" from "D:/project/TIMP/src/App.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67620:27)
    at onRollupWarning (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67648:9)
    at onwarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67364:13)
    at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
    at Object.logger [as onLog] (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
    at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18899:26
```

**Comment by H-Haynes** [comment]
忘了添加lodash-es库，安装下这个依赖即可
---- 回复的原邮件 ----
发件人 Nancy ***@***.***> 日期 2024年04月26日 17:37 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [H-Haynes/TIMP] 无法构建 (Issue #1) 
大佬你好，我拉下项目之后安装了依赖，但是无法构建，这个是报错
D:\project\TIMP>cnpm run compile > ***@***.*** compile > npm run app:build && electron-builder build --config .electron-builder.config.js --dir --config.asar=false > ***@***.*** app:build > vite build && electron-builder The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details. vite v5.2.10 building for production... ✓ 49 modules transformed. transforming (86) ***@***.***\node_modules\element-plus\es\components\carousel-item\style\index.mjsvite v5.2.10 building for production... ✓ 3 modules transformed. dist-electron/main/index.js 5.12 kB │ gzip: 2.05 kB ✓ built in 661ms vite v5.2.10 building for production... ✓ 1 modules transformed. dist-electron/preload/index.js 1.79 kB │ gzip: 0.85 kB ✓ built in 307ms x Build failed in 2.82s error during build: Error: [vite]: Rollup failed to resolve import "lodash-es" from "D:/project/TIMP/src/App.vue?vue&type=script&setup=true&lang.ts". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to `build.rollupOptions.external` at viteWarn ***@***.***/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67620:27) at onRollupWarning ***@***.***/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67648:9) at onwarn ***@***.***/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67364:13) at ***@***.***/node_modules/rollup/dist/es/shared/node-entry.js:18351:13 at Object.logger [as onLog] ***@***.***/node_modules/rollup/dist/es/shared/node-entry.js:19999:9) at ModuleLoader.handleInvalidResolvedId ***@***.***/node_modules/rollup/dist/es/shared/node-entry.js:18941:26) at ***@***.***/node_modules/rollup/dist/es/shared/node-entry.js:18899:26

**Comment by yuanshangyujingshierlou** [comment]
大佬，安装了依赖但是还是会报错,执行了npm run dist会报另一个错
```
PS D:\project\TIMP> npm run dist

> timp-music@2.0.0 dist
> npm run app:build & electron-builder


> timp-music@2.0.0 app:build
> vite build && electron-builder

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.2.10 building for production...
✓ 61 modules transformed.
transforming (76) src\assets\poster.jpgvite v5.2.10 building for production...
✓ 3 modules transformed.
dist-electron/main/index.js  5.12 kB │ gzip: 2.05 kB
✓ built in 432ms
vite v5.2.10 building for production...
✓ 1 modules transformed.
dist-electron/preload/index.js  1.79 kB │ gzip: 0.85 kB
✓ built in 155ms
x Build failed in 2.41s
error during build:
Error: [vite]: Rollup failed to resolve import "dayjs" from "D:/project/TIMP/src/views/video/detail.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67620:27)
    at onRollupWarning (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67648:9)
    at onwarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67364:13)
    at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
    at Object.logger [as onLog] (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
    at ModuleLoader.handleInvalidResolvedId (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
    at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18899:26
  • electron-builder  version=24.13.3 os=10.0.19045
  • loaded configuration  file=D:\project\TIMP\electron-builder.json5
  • writing effective config  file=release\2.0.0\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=30.0.1 appOutDir=release\2.0.0\win-unpacked
```

**Comment by yuanshangyujingshierlou** [comment]
这个是所有的依赖
```
{
  "name": "timp-music",
  "version": "2.0.0",
  "description": "TIMP音乐播放器",
  "author": "H-Haynes<3066620060@qq.com>",
  "license": "MIT",
  "private": true,
  "main": "dist-electron/main/index.js",
  "keywords": [
    "electron",
    "rollup",
    "vite",
    "vue3",
    "vue",
    "TIMP音乐"
  ],
  "debug": {
    "env": {
      "VITE_DEV_SERVER_URL": "http://127.0.0.1:3344/"
    }
  },
  "scripts": {
    "app:dev": "vite",
    "app:build": "vite build && electron-builder",
    "app:preview": "vite preview",
    "lint": "eslint --ext .js,.vue,.ts --ignore-path .gitignore --fix src",
    "format": "prettier .  --write",
    "deps:update": "taze major -I",
    "compile": "npm run app:build && electron-builder build --config .electron-builder.config.js --dir --config.asar=false",
    "dist": "npm run app:build & electron-builder"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.2",
    "@vue/eslint-config-typescript": "^12.0.0",
    "@vueuse/core": "^10.7.1",
    "autoprefixer": "^10.4.16",
    "electron": "^30.0.1",
    "electron-builder": "^24.9.1",
    "electron-builder-squirrel-windows": "^24.13.3",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.2",
    "eslint-plugin-vue": "^9.8.0",
    "pinia": "^2.1.7",
    "pinia-plugin-persist": "^1.0.0",
    "postcss": "^8.4.32",
    "prettier": "^3.1.1",
    "prettier-plugin-tailwindcss": "^0.5.10",
    "sass": "^1.69.7",
    "tailwindcss": "^3.4.0",
    "taze": "^0.13.1",
    "typescript": "^5.3.3",
    "unplugin-auto-import": "^0.17.3",
    "unplugin-element-plus": "^0.8.0",
    "vite": "^5.0.10",
    "vite-plugin-electron": "^0.15.5",
    "vite-plugin-electron-renderer": "^0.14.5",
    "vue": "^3.4.4",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.1.6",
    "vue-tsc": "^1.0.22"
  },
  "dependencies": {
    "@vue/devtools": "^7.0.20",
    "axios": "^1.6.5",
    "electron-devtools-installer": "^3.2.0",
    "element-plus": "^2.4.4",
    "lodash-es": "^4.17.21",
    "mitt": "^3.0.1",
    "normalize.css": "^8.0.1",
    "pinia-auto-refs": "^0.0.10",
    "qs": "^6.11.2",
    "throttle-debounce": "^5.0.0",
    "unocss": "^0.58.3",
    "unplugin-vue-components": "^0.26.0"
  }
}
```

**Comment by H-Haynes** [comment]
> 大佬，安装了依赖但是还是会报错,执行了npm run dist会报另一个错
> 
> ```
> PS D:\project\TIMP> npm run dist
> 
> > timp-music@2.0.0 dist
> > npm run app:build & electron-builder
> 
> 
> > timp-music@2.0.0 app:build
> > vite build && electron-builder
> 
> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
> vite v5.2.10 building for production...
> ✓ 61 modules transformed.
> transforming (76) src\assets\poster.jpgvite v5.2.10 building for production...
> ✓ 3 modules transformed.
> dist-electron/main/index.js  5.12 kB │ gzip: 2.05 kB
> ✓ built in 432ms
> vite v5.2.10 building for production...
> ✓ 1 modules transformed.
> dist-electron/preload/index.js  1.79 kB │ gzip: 0.85 kB
> ✓ built in 155ms
> x Build failed in 2.41s
> error during build:
> Error: [vite]: Rollup failed to resolve import "dayjs" from "D:/project/TIMP/src/views/video/detail.vue?vue&type=script&setup=true&lang.ts".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
>     at viteWarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67620:27)
>     at onRollupWarning (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67648:9)
>     at onwarn (file:///D:/project/TIMP/node_modules/.store/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:67364:13)
>     at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
>     at Object.logger [as onLog] (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
>     at ModuleLoader.handleInvalidResolvedId (file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
>     at file:///D:/project/TIMP/node_modules/.store/rollup@4.16.4/node_modules/rollup/dist/es/shared/node-entry.js:18899:26
>   • electron-builder  version=24.13.3 os=10.0.19045
>   • loaded configuration  file=D:\project\TIMP\electron-builder.json5
>   • writing effective config  file=release\2.0.0\builder-effective-config.yaml
>   • packaging       platform=win32 arch=x64 electron=30.0.1 appOutDir=release\2.0.0\win-unpacked
> ```

修复好了，部分依赖漏了
