### ISSUE TITLE
打包完的程序UI显示错误

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [H-Haynes/TIMP#2]
![image](https://github.com/H-Haynes/TIMP/assets/81788251/9bd6ff7a-557b-4e71-a73b-8259ae150582)

**Comment by yuanshangyujingshierlou** [comment]
功能按钮的图标不显示

**Comment by yuanshangyujingshierlou** [comment]
但是调试模式是正常的

**Comment by H-Haynes** [comment]
iconfont没有带https协议，已经修复好了

**Comment by yuanshangyujingshierlou** [comment]
> iconfont没有带https协议，已经修复好了
感谢大佬修复，大佬请问下有计划支持登陆吗，比如说我有网易和qq音乐的会员，我可以接入自己的账号去听vip歌曲吗？还有目前这个后台好像是大佬你的服务器呀，服务端可以自己部署吗

**Comment by H-Haynes** [comment]
后端代码里，音乐服务只是其中的一个小功能，还有些其他的功能,因此不太方便开源，登录功能有的平台暂未找到api，需要时间。有空我把服务端的代码抽离一下吧，其实相关的api目前都已有开源项目了

**Comment by yuanshangyujingshierlou** [comment]
> 后端代码里，音乐服务只是其中的一个小功能，还有些其他的功能,因此不太方便开源，登录功能有的平台暂未找到api，需要时间。有空我把服务端的代码抽离一下吧，其实相关的api目前都已有开源项目了

好的 谢谢大佬
